# Generated by Django 5.2 on 2026-03-01 17:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PenaltyCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_cause_notice_id', models.IntegerField(db_index=True, help_text='PK of the originating ShowCauseNotice (not a FK to avoid circular imports).')),
                ('hospital_id', models.CharField(db_index=True, max_length=50)),
                ('hospital_name', models.CharField(max_length=255)),
                ('hospital_email', models.EmailField(blank=True, default='', max_length=254)),
                ('district_name', models.CharField(blank=True, default='', max_length=100)),
                ('state_name', models.CharField(blank=True, default='', max_length=100)),
                ('penalty_type', models.CharField(choices=[('PENALTY', 'Closed with Penalty'), ('SUSPENSION', 'Closed with Suspension')], db_index=True, max_length=20)),
                ('penalty_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Imposed penalty in INR. Null for pure suspension cases.', max_digits=14, null=True)),
                ('suspension_until', models.DateField(blank=True, help_text="Fixed end date for suspension. Null means 'until penalty is paid'.", null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REMINDER_SENT', 'Reminder Sent'), ('PAID', 'Paid'), ('NON_COMPLIANT', 'Non-Compliant'), ('CLOSED', 'Closed')], db_index=True, default='ACTIVE', max_length=20)),
                ('imposed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reminder_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=150)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-imposed_at'],
                'indexes': [models.Index(fields=['hospital_id', 'status'], name='pmjay_fraud_hospita_5b3b81_idx')],
            },
        ),
        migrations.CreateModel(
            name='PenaltyAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('IMPOSED', 'Penalty Imposed'), ('REMINDER_SENT', 'Reminder Notice Sent'), ('MARKED_PAID', 'Penalty Marked as Paid'), ('MARKED_NON_COMPLIANT', 'Marked Non-Compliant'), ('CLOSED', 'Case Closed'), ('EMAIL_FAILED', 'Email Send Failed')], max_length=30)),
                ('performed_by', models.CharField(max_length=150)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('penalty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='pmjay_fraud_dashboard_penalty_engine.penaltycase')),
            ],
            options={
                'ordering': ['performed_at'],
            },
        ),
    ]
