SHAPEFILE_DISTRICT_MAPPING = {
    "sheohar": 1,
    "sitamarhi": 2,
    "madhubani": 3,
    "supaul": 4,
    "araria": 5,
    "purnia": 6,
    "katihar": 7,
    "madhepura": 8,
    "saharsa": 9,
    "darbhanga": 10,
    "muzaffarpur": 11,
    "gopalganj": 12,
    "siwan": 13,
    "saran": 14,
    "vaishali": 15,
    "samastipur": 16,
    "begusarai": 17,
    "khagaria": 18,
    "bhagalpur": 19,
    "banka": 20,
    "munger": 21,
    "lakhisarai": 22,
    "sheikhpura": 23,
    "nalanda": 24,
    "patna": 25,
    "bhojpur": 26,
    "kaimur": 27,
    "rohtas": 28,
    "aurangabad": 29,
    "gaya": 30,
    "nawada": 31,
    "jamui": 32,
    "jehanabad": 33,
    "arwal": 34,
    "east champaran": 35,
    "purbi champaran": 35,
    "kishanganj": 36,
    "buxar": 37,
    "west champaran": 38,
}
