# Generated by Django 5.1.7 on 2025-08-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmjay_fraud_dashboard_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='last24hour',
            name='preauth_init_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
