# Generated by Django 5.1.7 on 2025-08-16 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmjay_fraud_dashboard_app', '0002_alter_last24hour_preauth_init_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='last24hour',
            unique_together={('registration_id', 'preauth_init_date')},
        ),
    ]
