# Generated by Django 5.1.7 on 2025-08-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmjay_fraud_dashboard_app', '0003_alter_last24hour_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='last24hour',
            name='admission_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
