# Generated by Django 5.1.7 on 2025-08-23 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmjay_fraud_dashboard_app', '0004_alter_last24hour_admission_dt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitalbeds',
            old_name='hospital_id',
            new_name='hospital_code',
        ),
    ]
