# Generated by Django 5.2.9 on 2025-12-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmjay_fraud_dashboard_app', '0005_rename_hospital_id_hospitalbeds_hospital_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspicioushospital',
            name='district',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
