# Generated by Django 5.2.9 on 2025-12-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmjay_fraud_dashboard_app', '0006_suspicioushospital_district'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='last24hour',
            name='pmjay_fraud_hospita_86daca_idx',
        ),
        migrations.RenameField(
            model_name='hospitalbeds',
            old_name='hospital_code',
            new_name='hospital_id',
        ),
        migrations.RenameField(
            model_name='last24hour',
            old_name='hospital_code',
            new_name='hospital_id',
        ),
        migrations.AddIndex(
            model_name='last24hour',
            index=models.Index(fields=['hospital_id'], name='pmjay_fraud_hospita_5b83b9_idx'),
        ),
    ]
