# Generated by Django 5.2 on 2025-12-29 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmjay_fraud_dashboard_app', '0007_remove_last24hour_pmjay_fraud_hospita_86daca_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='last24hour',
            name='pmjay_fraud_hospita_42e918_idx',
        ),
        migrations.RemoveIndex(
            model_name='last24hour',
            name='pmjay_fraud_admissi_f8d150_idx',
        ),
        migrations.RemoveIndex(
            model_name='last24hour',
            name='pmjay_fraud_patient_e4f2ba_idx',
        ),
        migrations.RemoveIndex(
            model_name='last24hour',
            name='pmjay_fraud_age_29f859_idx',
        ),
        migrations.RemoveIndex(
            model_name='last24hour',
            name='pmjay_fraud_hospita_5b83b9_idx',
        ),
        migrations.AlterUniqueTogether(
            name='last24hour',
            unique_together=set(),
        ),
    ]
