# Generated by Django 5.2 on 2026-02-19 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmjay_fraud_dashboard_app', '0008_remove_last24hour_pmjay_fraud_hospita_42e918_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalbeds',
            name='hospital_district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospitalbeds',
            name='hospital_email_id',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalbeds',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='last24hour',
            unique_together={('registration_id', 'preauth_init_date')},
        ),
        migrations.AddIndex(
            model_name='hospitalbeds',
            index=models.Index(fields=['hospital_district'], name='pmjay_fraud_hospita_5413bb_idx'),
        ),
        migrations.AddIndex(
            model_name='last24hour',
            index=models.Index(fields=['hospital_type', 'category_details'], name='pmjay_fraud_hospita_dff9b1_idx'),
        ),
        migrations.AddIndex(
            model_name='last24hour',
            index=models.Index(fields=['admission_dt'], name='pmjay_fraud_admissi_f8d150_idx'),
        ),
        migrations.AddIndex(
            model_name='last24hour',
            index=models.Index(fields=['patient_district_name'], name='pmjay_fraud_patient_e4f2ba_idx'),
        ),
        migrations.AddIndex(
            model_name='last24hour',
            index=models.Index(fields=['age'], name='pmjay_fraud_age_29f859_idx'),
        ),
        migrations.AddIndex(
            model_name='last24hour',
            index=models.Index(fields=['hospital_id'], name='pmjay_fraud_hospita_5b83b9_idx'),
        ),
    ]
