# Generated by Django 5.2 on 2026-06-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pmjay_fraud_dashboard_app", "0009_hospitalbeds_hospital_district_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="last24hour",
            index=models.Index(
                fields=["preauth_init_date"], name="pmjay_fraud_preauth_eb5e66_idx"
            ),
        ),
    ]
