# Generated by Django 5.2 on 2026-06-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pmjay_fraud_dashboard_app", "0010_last24hour_pmjay_fraud_preauth_eb5e66_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="last24hour",
            name="procedure_details",
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
