# Generated by Django 5.2 on 2026-06-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pmjay_fraud_dashboard_app", "0011_alter_last24hour_procedure_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="last24hour",
            name="category_details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="procedure_details",
            field=models.TextField(blank=True, null=True),
        ),
    ]
