# Generated by Django 5.2 on 2026-06-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pmjay_fraud_dashboard_app",
            "0012_alter_last24hour_category_details_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospitalbeds",
            name="hospital_district",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hospitalbeds",
            name="hospital_id",
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name="hospitalbeds",
            name="hospital_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="aco_approved_date",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="aco_user",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="admission_type",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="ben_ifsc_code",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="careplan_desc",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="case_id",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="case_status",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="case_type",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="claim_approved_date",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="claim_init_date",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="claim_rejected_date",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="cpd_approved_date",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="cpd_user",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="current_workflow_role",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="current_workflow_user",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="death_dt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="discharge_dt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="discharge_type",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="family_id",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="gender",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="hosp_account_number",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="hosp_district_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="hosp_pan_number",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="hosp_state_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="hospital_district_cd",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="hospital_id",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="hospital_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="hospital_state_cd",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="hospital_type",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="last_insert_dt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="m_flag",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="member_id",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="paid_flag",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="patient_district_code",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="patient_district_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="patient_dob",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="patient_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="patient_state_code",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="patient_state_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="payment_paid_dt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="policy_code",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="preauth_approved_date",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="preauth_rejected_date",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="procedure_code",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="registration_id",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="renewal_code",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="service_request_type",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="sha_approved_date",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="sha_user",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="speciality_code",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="src_account_no",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="src_ifsc_code",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="status_id_pk",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="surgery_dt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="last24hour",
            name="utr_no",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="suspicioushospital",
            name="district",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="suspicioushospital",
            name="hospital_id",
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name="suspicioushospital",
            name="hospital_name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="uploadhistory",
            name="filename",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="uploadhistory",
            name="model_type",
            field=models.TextField(
                choices=[
                    ("suspicious", "Suspicious Hospital List"),
                    ("beds", "Hospital Beds"),
                ],
                unique=True,
            ),
        ),
    ]
