# Generated by Django 5.2 on 2026-02-16 13:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShowCauseNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_id', models.CharField(max_length=50)),
                ('hospital_name', models.CharField(max_length=255)),
                ('district_name', models.CharField(blank=True, max_length=255, null=True)),
                ('analytics_start_date', models.DateField()),
                ('analytics_end_date', models.DateField()),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('REMINDER_1', 'First Reminder Sent'), ('REMINDER_2', 'Second Reminder Sent'), ('CLOSED', 'Closed'), ('EXPIRED', 'Expired')], default='SENT', max_length=20)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reminder_1_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_2_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=100)),
            ],
            options={
                'indexes': [models.Index(fields=['hospital_id'], name='pmjay_fraud_hospita_4c602e_idx'), models.Index(fields=['status'], name='pmjay_fraud_status_00abfa_idx')],
                'unique_together': {('hospital_id', 'analytics_start_date', 'analytics_end_date')},
            },
        ),
    ]
