# Generated by Django 5.2 on 2026-02-18 21:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmjay_fraud_dashboard_show_cause_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowCauseAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ISSUED', 'Notice Issued'), ('REMINDER_1_SENT', 'Reminder 1 Sent'), ('REMINDER_2_SENT', 'Reminder 2 Sent'), ('CLOSED', 'Notice Closed'), ('EXPIRED', 'Marked as Expired'), ('EMAIL_FAILED', 'Email Send Failed')], max_length=30)),
                ('performed_by', models.CharField(max_length=150)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['performed_at'],
            },
        ),
        migrations.RemoveField(
            model_name='showcausenotice',
            name='sent_at',
        ),
        migrations.AddField(
            model_name='showcausenotice',
            name='case_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='showcausenotice',
            name='case_type',
            field=models.CharField(choices=[('OPTHALMOLOGY', 'Opthalmology')], default='OPTHALMOLOGY', max_length=50),
        ),
        migrations.AddField(
            model_name='showcausenotice',
            name='hospital_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='showcausenotice',
            name='issued_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='showcausenotice',
            name='created_by',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='showcausenotice',
            name='status',
            field=models.CharField(choices=[('ISSUED', 'Issued'), ('REMINDER_1_SENT', '1st Reminder Sent'), ('REMINDER_2_SENT', '2nd Reminder Sent'), ('EXPIRED', 'Expired'), ('CLOSED', 'Closed by Officer')], default='ISSUED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='showcausenotice',
            index=models.Index(fields=['issued_at'], name='pmjay_fraud_issued__eef44f_idx'),
        ),
        migrations.AddField(
            model_name='showcauseauditlog',
            name='notice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='pmjay_fraud_dashboard_show_cause_engine.showcausenotice'),
        ),
        migrations.AddIndex(
            model_name='showcauseauditlog',
            index=models.Index(fields=['notice', 'performed_at'], name='pmjay_fraud_notice__e8ae01_idx'),
        ),
    ]
