# Generated by Django 5.2 on 2026-02-20 03:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmjay_fraud_dashboard_show_cause_engine', '0002_showcauseauditlog_remove_showcausenotice_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showcausenotice',
            options={'ordering': ['-issued_at']},
        ),
        migrations.RemoveIndex(
            model_name='showcauseauditlog',
            name='pmjay_fraud_notice__e8ae01_idx',
        ),
        migrations.RemoveIndex(
            model_name='showcausenotice',
            name='pmjay_fraud_hospita_4c602e_idx',
        ),
        migrations.RemoveIndex(
            model_name='showcausenotice',
            name='pmjay_fraud_status_00abfa_idx',
        ),
        migrations.RemoveIndex(
            model_name='showcausenotice',
            name='pmjay_fraud_issued__eef44f_idx',
        ),
        migrations.RemoveField(
            model_name='showcausenotice',
            name='case_count',
        ),
        migrations.AddField(
            model_name='showcausenotice',
            name='age_violation_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='showcausenotice',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='showcausenotice',
            name='ot_violation_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='showcausenotice',
            name='preauth_violation_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='showcausenotice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='showcauseauditlog',
            name='action',
            field=models.CharField(choices=[('ISSUED', 'Notice Issued'), ('REMINDER_1_SENT', '1st Reminder Sent'), ('REMINDER_2_SENT', '2nd Reminder Sent'), ('EXPIRED', 'Notice Expired'), ('AUTO_EXPIRED', 'Auto-Expired by System'), ('CLOSED', 'Closed by Officer'), ('EMAIL_FAILED', 'Email Send Failed')], max_length=30),
        ),
        migrations.AlterField(
            model_name='showcausenotice',
            name='case_type',
            field=models.CharField(choices=[('OPTHALMOLOGY', 'Opthalmology')], default='OPTHALMOLOGY', max_length=20),
        ),
        migrations.AlterField(
            model_name='showcausenotice',
            name='district_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='showcausenotice',
            name='issued_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='showcausenotice',
            name='status',
            field=models.CharField(choices=[('ISSUED', 'Issued'), ('REMINDER_1_SENT', '1st Reminder Sent'), ('REMINDER_2_SENT', '2nd Reminder Sent'), ('EXPIRED', 'Expired'), ('CLOSED', 'Closed by Officer')], db_index=True, default='ISSUED', max_length=20),
        ),
    ]
